version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dsmovie"
    ports:
      - "5432:5432"
    volumes:
      - .:/usr/database
